/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#505c8a",
        "outline": "#767680",
        "surface-container-highest": "#dde3ed",
        "outline-variant": "#c6c6d0",
        "inverse-surface": "#2b3138",
        "tertiary-fixed-dim": "#b6c4ff",
        "secondary": "#bb0020",
        "on-secondary-container": "#fffbff",
        "background": "#f7f9ff",
        "primary-fixed": "#dce1ff",
        "on-tertiary-fixed-variant": "#304381",
        "surface": "#f7f9ff",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#410005",
        "surface-container-low": "#eef4fe",
        "on-primary-fixed-variant": "#384571",
        "secondary-fixed-dim": "#ffb3af",
        "on-primary-container": "#8b97c9",
        "primary-container": "#222f5a",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#00164e",
        "secondary-container": "#e7102d",
        "surface-container-high": "#e3e9f2",
        "primary-fixed-dim": "#b8c4f9",
        "tertiary-container": "#182d6a",
        "inverse-primary": "#b8c4f9",
        "surface-bright": "#f7f9ff",
        "on-primary-fixed": "#091843",
        "surface-dim": "#d4dae4",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "on-surface-variant": "#45464f",
        "tertiary": "#001751",
        "inverse-on-surface": "#ebf1fb",
        "primary": "#0a1944",
        "secondary-fixed": "#ffdad7",
        "on-secondary-fixed-variant": "#930017",
        "on-surface": "#161c23",
        "on-tertiary-container": "#8497da",
        "tertiary-fixed": "#dce1ff",
        "error": "#ba1a1a",
        "surface-container": "#e8eef8",
        "on-background": "#161c23",
        "surface-variant": "#dde3ed",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
}
